[package]
name = "mm-exact"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
malachite = { version = "=0.10.0", default-features = false, features = ["naturals_and_integers", "rationals"] }
mm-core = { path = "../mm-core" }
mm-rat = { path = "../mm-rat" }
mm-schema = { path = "../mm-schema" }

[lints]
workspace = true
