import MatrixMath.Numeric.Log2Bounds
import Lean.Data.Json

/-!
Lean-side series-length check (`docs/specs/0002_spec.md` §4.2).

Evaluates the compiled `MatrixMath.Numeric.seriesLength` on the committed
vectors of `tests/vectors/series-length.json` and prints what it selects. The
vector file is committed data: nothing here regenerates it, and a table
regenerated by an implementation would only prove that the implementation agrees
with itself.

The printed values are what `scripts/differential-check.py` compares against
Rust and Python, so this script is the Lean side of §12.6 for L3 and not merely
a self-test. It also fails locally when Lean disagrees with the file, so a
mismatch is visible without the harness.

Run through the harness with `just test-diff`, or on its own with
`just lean-series-length-check`.
-/

open Lean MatrixMath.Numeric

/-- One committed vector: the series variable, the precision, and the normative
length Appendix A records. -/
structure SeriesVector where
  note : String
  z : ℚ
  precision : ℕ
  terms : ℕ

/-- Read a §6.2 canonical rational object `{"d": "...", "n": "..."}`. -/
def parseRational (value : Json) : Except String ℚ := do
  let numerator ← (← value.getObjVal? "n").getStr?
  let denominator ← (← value.getObjVal? "d").getStr?
  let some n := numerator.toInt? | throw s!"malformed numerator {numerator}"
  let some d := denominator.toNat? | throw s!"malformed denominator {denominator}"
  if d = 0 then throw "zero denominator" else pure ((n : ℚ) / (d : ℚ))

def parseVector (value : Json) : Except String SeriesVector := do
  let note ← (← value.getObjVal? "note").getStr?
  let z ← parseRational (← value.getObjVal? "z")
  let precision ← (← value.getObjVal? "precision").getNat?
  let terms ← (← value.getObjVal? "terms").getNat?
  pure { note, z, precision, terms }

def parseVectors (text : String) : Except String (Array SeriesVector) := do
  let document ← Json.parse text
  let entries ← (← document.getObjVal? "vectors").getArr?
  entries.mapM parseVector

def main : IO UInt32 := do
  let text ← IO.FS.readFile "../tests/vectors/series-length.json"
  match parseVectors text with
  | .error e =>
      IO.eprintln s!"lean-series-length-check: {e}"
      return 1
  | .ok vectors => do
      let mut failures := 0
      for v in vectors do
        let selected := seriesLength v.z v.precision
        -- The machine-readable line `scripts/differential-check.py` reads.
        IO.println s!"series-length {v.z.num}/{v.z.den} {v.precision} {selected}"
        if selected != v.terms then
          IO.eprintln s!"FAIL z={v.note} precision={v.precision}: \
Lean selected {selected}, Appendix A records {v.terms}"
          failures := failures + 1
      if failures = 0 then
        IO.println s!"lean-series-length-check: {vectors.size} vectors, all lengths as recorded"
        return 0
      else
        IO.eprintln s!"lean-series-length-check: {failures} failures"
        return 1
